FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

# copy the applicaton code 
COPY . .

RUN npm run build


FROM node:24.12-alpine3 AS production

WORKDIR /app

COPY --from=build  /app/dist ./dist


CMD [ "npm" , "run", "start:prod" ]

